@startuml
class Square{
int x
int y
getX()
getY()
setX()
setY()
}

class Piece{
Piece(int x, int y)
virtual void move(vector<vector<Piece>>
virtual void print()
virtual bool isMoveValid
}

class Board{
vector<vector<Piece*>> boardFields
const &getBoardFields const
void setBoardFields(const vector<vector<Piece*>> &boardFields
void initialize()
Piece* getBoardField(int x, int y)
void printBoard()
void setBoardField(Piece* piece)
}

class MoveUtil{
static void setAnyValidateMovePoint(int* x, int* y)
static bool isFriendlyFire(vector<vector<Piece *>> array, int x, int y)
}

Square --|> Piece

@enduml